# Generated by Django 3.0.8 on 2020-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankinterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_Name', models.CharField(max_length=50)),
                ('Paid_Date', models.DateField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Investment', models.CharField(max_length=50)),
                ('Investment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer', models.CharField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Date_of_Pay', models.DateField()),
                ('Payment', models.IntegerField()),
                ('Return_Pay_Date', models.DateField()),
                ('Total_Days', models.IntegerField()),
                ('Rate_Of_Interest', models.IntegerField()),
                ('Interest', models.IntegerField()),
            ],
        ),
    ]
