# Generated by Django 3.0.8 on 2020-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_table',
            name='Return_Pay_Date',
            field=models.DateField(null=True),
        ),
    ]
