# Generated by Django 3.0.8 on 2020-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200911_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_table',
            name='Interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logs_table',
            name='Rate_Of_Interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logs_table',
            name='Total_Days',
            field=models.IntegerField(null=True),
        ),
    ]
