# Generated by Django 3.0.8 on 2020-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200911_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_table',
            name='Interest',
            field=models.FloatField(null=True),
        ),
    ]
