# Generated by Django 3.0.8 on 2020-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200912_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinterest',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
