# Generated by Django 3.0.8 on 2020-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200912_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinterest',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
