# Generated by Django 3.1.1 on 2020-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200912_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_table',
            name='Total',
            field=models.FloatField(null=True),
        ),
    ]
