# Generated by Django 3.1.1 on 2020-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_logs_table_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returninvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To_Return_Investment', models.CharField(max_length=50)),
                ('Return_Investment_Date', models.DateField(null=True)),
                ('Investment_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='Investment_Date',
            field=models.DateField(null=True),
        ),
    ]
