# Generated by Django 3.1.1 on 2020-10-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201022_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvestment',
            name='id1',
            field=models.IntegerField(null=True),
        ),
    ]
